<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => '创建时间',
    'Description' => '描述',
    'Logo' => 'Logo',
    'Name' => '链接名称',
    'Type ID' => '类别',
    'Updated At' => '更新时间',
    'Url' => '',
    'User ID' => 'User',
    'Create Link' => '创建链接',
    'Create Type' => '创建类别',
    'Delete Link' => '删除链接',
    'Delete Type' => '删除类别',
    'Manage Link' => '链接管理',
    'Manage Type' => '类别管理',
    'Type' => '类别',
    'Update Link' => '更新链接',
    'Update Type' => '更新类别',
    'User' => '用户',
];
